package com.nullify.ui.theme

import androidx.compose.ui.graphics.Color

val NullifyPrimary = Color(0xFF1B5E20)
val NullifyOnPrimary = Color(0xFFFFFFFF)
val NullifyPrimaryContainer = Color(0xFFA5D6A7)
val NullifyOnPrimaryContainer = Color(0xFF0D3310)

val NullifySecondary = Color(0xFF37474F)
val NullifyOnSecondary = Color(0xFFFFFFFF)
val NullifySecondaryContainer = Color(0xFFCFD8DC)
val NullifyOnSecondaryContainer = Color(0xFF1C2529)

val NullifyTertiary = Color(0xFF00695C)
val NullifyOnTertiary = Color(0xFFFFFFFF)
val NullifyTertiaryContainer = Color(0xFF80CBC4)
val NullifyOnTertiaryContainer = Color(0xFF00201A)

val NullifyError = Color(0xFFB71C1C)
val NullifyOnError = Color(0xFFFFFFFF)
val NullifyErrorContainer = Color(0xFFFFCDD2)
val NullifyOnErrorContainer = Color(0xFF7F1010)

val NullifyBackground = Color(0xFFF5F5F5)
val NullifyOnBackground = Color(0xFF1C1B1F)
val NullifySurface = Color(0xFFFFFFFF)
val NullifyOnSurface = Color(0xFF1C1B1F)
val NullifySurfaceVariant = Color(0xFFE8E8E8)
val NullifyOnSurfaceVariant = Color(0xFF49454F)
val NullifyOutline = Color(0xFF79747E)

// Material 3 1.2+ & 1.3+ Surface Container & Inverse Tokens (Light)
val NullifySurfaceDimLight = Color(0xFFDADADA)
val NullifySurfaceBrightLight = Color(0xFFFBFBFB)
val NullifySurfaceContainerLowestLight = Color(0xFFFFFFFF)
val NullifySurfaceContainerLowLight = Color(0xFFF4F6F4)
val NullifySurfaceContainerLight = Color(0xFFEEF1EE)
val NullifySurfaceContainerHighLight = Color(0xFFE8ECE8)
val NullifySurfaceContainerHighestLight = Color(0xFFE2E7E2)
val NullifyOutlineVariantLight = Color(0xFFC4C7C5)
val NullifyScrim = Color(0xFF000000)
val NullifyInverseSurfaceLight = Color(0xFF2E312E)
val NullifyInverseOnSurfaceLight = Color(0xFFEFF1EE)
val NullifyInversePrimaryLight = Color(0xFFA5D6A7)

// Material 3 1.2+ & 1.3+ Surface Container & Inverse Tokens (Dark)
val NullifySurfaceDimDark = Color(0xFF111411)
val NullifySurfaceBrightDark = Color(0xFF373A37)
val NullifySurfaceContainerLowestDark = Color(0xFF0C0F0C)
val NullifySurfaceContainerLowDark = Color(0xFF191C19)
val NullifySurfaceContainerDark = Color(0xFF1D201D)
val NullifySurfaceContainerHighDark = Color(0xFF282B28)
val NullifySurfaceContainerHighestDark = Color(0xFF333633)
val NullifyOutlineVariantDark = Color(0xFF424942)
val NullifyInverseSurfaceDark = Color(0xFFE1E3DF)
val NullifyInverseOnSurfaceDark = Color(0xFF2E312E)
val NullifyInversePrimaryDark = Color(0xFF1B5E20)

// Glassmorphism — gradient backgrounds
val GlassGradientStartLight = Color(0xFFE8F5E9)
val GlassGradientMidLight = Color(0xFFE0F2F1)
val GlassGradientEndLight = Color(0xFFE3F2FD)
val GlassGradientStartDark = Color(0xFF1B2E1B)
val GlassGradientMidDark = Color(0xFF1A2E2D)
val GlassGradientEndDark = Color(0xFF0D2338)

// Glassmorphism — surface tint (applied via copy(alpha =))
val GlassBorderLight = Color(0x4DFFFFFF)
val GlassBorderDark = Color(0x1AFFFFFF)
